### PR TITLE
Fix multicast-bypass not working

### PR DESCRIPTION
**Pull request by HyperGH**
### Description
Currently there exists an issue where no matter your client configuration, the client will always attempt to do multicasting, even if a port is explicitly provided, and `do_multicast` is set to False server-side. This PR tries to fix that, and although this fixed the issue in my project, it could still be flawed in some other way I could not foresee.

### Checklist

- [x] This PR has been tested.

### CODE REVIEW

**Review by ShineyDev — APPROVED** [review]
Hey, thanks for the PR! Since it closes #42 I'll merge now.

cc @lgaan

**Review by ShineyDev — CHANGES_REQUESTED** [review]
Looks like I spoke too soon. Appease the linter and I'll let this through.

**Comment by HyperGH** [comment]
Done!

**Review by ShineyDev — APPROVED** [review]
Thanks.

**Pull request merged**
