### PR TITLE
Fix cog reloading not reloading IPC routes

### PR DESCRIPTION
**Pull request by Skelmis**
### Description
Previously when reloading a cog with attached IPC routes, the server would not update the endpoints. This resolves that.

Resolved it by removing the un-needed `endpoints` attribute and relying on `ROUTES` for two reasons:
 - Firstly, `**` unpacking favours one side, so this could lead to issues with updating
 - Secondly, `update_endpoints` was only called on initial creation. Further requests would always be from [here](https://github.com/Ext-Creators/discord-ext-ipc/blob/main/discord/ext/ipc/server.py#L141) which wouldn't mean endpoints got updated.
     - Note, adding `update_endpoints` within this didn't appear to resolve the issue during my albiet short testing 

### Checklist
- [x] This PR has been tested.

### CODE REVIEW

**Review by jgayfer — APPROVED** [review]
+1 Tested and resolves routes not being reloaded, for both new and modified routes.

**Review by ShineyDev — CHANGES_REQUESTED** [review]
Thanks for the PR!

Unfortunately, the implementation you've provided will update the `ROUTES` attribute for all instances of `Server` due to the nature of class attributes.

<details>
<summary>Here's a reproduction.</summary>

```python3
>>> class Foo:
...     ROUTES = dict()
...
>>> Foo.ROUTES["a"] = 1
>>>
>>> foo = Foo()
>>> foo.ROUTES
{'a': 1}
>>>
>>> foo.ROUTES["b"] = 2
>>> foo.ROUTES
{'a': 1, 'b': 2}
>>>
>>> Foo.ROUTES
{'a': 1, 'b': 2}
>>>
>>> foo2 = Foo()
>>> foo2.ROUTES
{'a': 1, 'b': 2}
>>>
>>> foo2.ROUTES["c"] = 3
>>> foo2.ROUTES
{'a': 1, 'b': 2, 'c': 3}
>>>
>>> foo.ROUTES
{'a': 1, 'b': 2, 'c': 3}
>>>
>>> Foo.ROUTES
{'a': 1, 'b': 2, 'c': 3}
```
</details>

**Comment by Skelmis** [comment]
> Thanks for the PR!
> 
> Unfortunately, the implementation you've provided will update the `ROUTES` attribute for all instances of `Server` due to the nature of class attributes.
> Here's a reproduction.

I beg to differ. `ROUTES` are not shared between process's (during my tests) and you wouldn't (In theory) start more then one ipc server per bot

**Comment by Skelmis** [comment]
Logan expressed favour of #44, and I see no need to continue this.

**Pull request closed without merging**
