### PR TITLE
Delay reconnection

### PR DESCRIPTION
**Pull request by sohamb03**
### Description

As per @lgaan's comment in #26 

### Checklist

- [x ] This PR has been tested.

### CODE REVIEW

**Comment by lgaan** [comment]
Looks fine to me, fix the linter errors and this will be good to merge.

**Comment by sohamb03** [comment]
> Looks fine to me, fix the linter errors and this will be good to merge.

Looks like it was an issue with GitHub API which caused the workflow to fail. `Failed to call GitHub Status API`

**Comment by ShineyDev** [comment]
No, the linter failed expectedly on your indented empty lines. The status API failing doesn't modify the status of the workflow run.

**Review by ShineyDev — APPROVED** [review]
Thanks for the PR. 🎉

**Pull request merged**
